export enum UserRole {
  EMPLOYEE = "EMPLOYEE",
  HR_COORDINATOR = "HR_COORDINATOR",
  HR_OPERATIONS_MANAGER = "HR_OPERATIONS_MANAGER",
  COMPLIANCE_REVIEWER = "COMPLIANCE_REVIEWER",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export const mutableHRRoles = [
  UserRole.HR_COORDINATOR,
  UserRole.HR_OPERATIONS_MANAGER,
  UserRole.SUPER_ADMIN,
] as const;